name: "Build the python code and wheels"
description: "Common Python build steps"
inputs:
  type:
    description: python_version
    required: true
  whylabs_api_key:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      name: Install Python
      with:
        python-version: ${{ inputs.python_version }}

    - uses: Gr1N/setup-poetry@v8
      name: Install poetry
      with:
        poetry-version: 1.7.1

    - name: Install python dependencies
      shell: bash
      run: make install

    - name: Check types
      shell: bash
      run: make lint

    - name: Check formatting
      shell: bash
      run: make format

    - name: Run test
      shell: bash
      env:
        WHYLABS_API_KEY: ${{ inputs.whylabs_api_key }}
      run: make test

    - name: Make dists
      shell: bash
      run: make dist

    - name: Upload python client wheel
      uses: actions/upload-artifact@v4
      with:
        name: langkit-wheel_${{ inputs.python_version }}
        path: dist/*.whl
